#!/usr/bin/env php
<?php

use Lando\BuildCommand;
use Lando\CommandSettings;
use Lando\TestCommand;
use Symfony\Component\Console\Application;
use Symfony\Component\Dotenv\Dotenv;

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('LANDO_COMPOSER_INSTALL', $file);
        break;
    }
}
unset($file);
if (!defined('LANDO_COMPOSER_INSTALL')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );
    die(1);
}

require LANDO_COMPOSER_INSTALL;

$settings = new CommandSettings();
$app = new Application('lando', '0.0.1');
if ($settings->isDevelopmentEnvironment()) {
    (new Dotenv())->load(__DIR__ . '/.env');
    $app->addCommands([new TestCommand($settings)]);
    $app->setDefaultCommand('test', true);
} else {
    $app->addCommands([new BuildCommand($settings)]);
    $app->setDefaultCommand('build', true);
}
$app->run();